# Generated by Django 3.1.7 on 2021-05-11 14:51

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JugadorO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMovimiento', models.CharField(default='O', max_length=1)),
                ('lastMovement', models.IntegerField(default=None)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JugadorX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMovimiento', models.CharField(default='X', max_length=1)),
                ('lastMovement', models.IntegerField(default=None)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('token', models.CharField(default=api.models.generate_token, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=api.models.generate_code, max_length=8, unique=True)),
                ('finished', models.BooleanField(default=False)),
                ('message', models.CharField(default='', max_length=30)),
                ('turno', models.BooleanField(default=False)),
                ('tablero', models.CharField(default='[s,s,s,s,s,s,s,s,s]', max_length=50)),
                ('jugadorO', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.jugadoro')),
                ('jugadorX', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.jugadorx')),
            ],
        ),
    ]
