# Generated by Django 3.1.7 on 2021-05-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210511_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadoro',
            name='lastMovement',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jugadorx',
            name='lastMovement',
            field=models.IntegerField(default=1),
        ),
    ]
