# Generated by Django 3.1.7 on 2021-05-11 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_partida_jugadoro'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='jugadorO',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.jugadoro'),
        ),
        migrations.AlterField(
            model_name='jugadoro',
            name='lastMovement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jugadorx',
            name='lastMovement',
            field=models.IntegerField(default=0),
        ),
    ]
