# Generated by Django 3.1.7 on 2021-05-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210511_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadoro',
            name='lastMovement',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorx',
            name='lastMovement',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='jugadorO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jugadoro'),
        ),
    ]
