# Generated by Django 3.1.7 on 2021-05-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_persona_enpartida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
