# Generated by Django 3.1.7 on 2021-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210511_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='turno',
            field=models.BooleanField(default=True),
        ),
    ]
