# Generated by Django 3.1.7 on 2021-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210512_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='cantidad',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
